---
name: build image

"on":
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t "bookstore-backend" .
        working-directory: ./backend

      - name: Tag Docker Image
        run: docker tag "bookstore-backend" "${{ secrets.DOCKERHUB_USERNAME }}/bookstore-backend:latest"
        working-directory: ./backend

      - name: Push Image to DockerHub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/bookstore-backend:latest"
        working-directory: ./backend
